services:
  - type: web
    name: weather-agent
    runtime: python
    buildCommand: ""
    startCommand: uvicorn remote_agent:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
